# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Maven
      run: mvn -B package --file pom.xml
